apiVersion: v1
kind: Service
metadata:
  name: grpcbin
spec:
  ports:
  - port: 9000
    name: insecure9000
    #appProtocol: grpc
  - port: 9001
    name: secure9001
    #appProtocol: grpc
  - port: 443
    name: secure443
    #appProtocol: grpc
  selector:
    app: grpcbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcbin
spec:
  selector:
    matchLabels:
      app: grpcbin
  template:
    metadata:
      labels:
        app: grpcbin
    spec:
      containers:
      - image: moul/grpcbin
        name: grpcbin
        ports:
        - containerPort: 9000
          name: insecure9000
        - containerPort: 9001
          name: secure9001
        - containerPort: 443
          name: secure443